### ISSUE TITLE
mangas.length return 0

### ISSUE THREAD

**Issue by gorgoserio** [posva/mangare#1]
Hi, first of all very nice app, bravo! 
When i run the app in 'http://localhost:8080/search' i can't search anything, because the fetching of the list of mangas return 0.

"logger.info(`Retrieved ${mangas.length} manga`)"

I run all the test, and the app works fine, maybe is a cross origin issue? 

Thanks in advance!

**Comment by posva** [comment]
Oh hi @gordonwes I'm sorry I never saw your issue!
I'm now watching my own repo as I should have been doing from the beginning.
That's because you have to populate the database. It has been a long time since the last time I did that but you should be able to get the real application running by `./tasks/update-manga-list`
Please tell me if that solves the issue for you 😉 
I'd love to hear more feedback once you can use the whole application!

**Comment by posva** [comment]
Hey @gordonwes , I'm closing the issue since it should be solved with the command I gave you. I'd appreciate if you could give me your thoughts about Mangare 😄
